### PR TITLE
Create starting menu using UI builder

### LINKED ISSUE #1: Feature Request: {UX Menu}
**Description:**
Create a UI for player to select starting the game or quit the game.

**Use Case:**
This is import because it's where player start the game.

**Proposed Solution:**
Creating a simple start game and quit game menu with the function of starting the program or exit the program.

**Additional Information:**
Please keep in mind the game has a narrative story, implementation should allow changes to include or possibly images/background ambient songs to be added.

### PR DESCRIPTION
**Pull request by Carlson-Lee**
Starting Scene is completed with Minimal functionality, start button it's currently taking you to a empty scene which shows a complete blue screen. The exit button will exit Unity Game Editor Application, and should exit the application on a stand alone build.

To implement the start scene to the correct scene, make sure the scene comes after the UI Toolkit scene.
image

### CODE REVIEW

**Review by DevonHenderson — APPROVED** [review]
# Code Review

## Functional Requirements
_Is the application fit for purpose? Does it meet the the user’s requirements and properly address the issue?_  

 - Yes, this is useful for adding a titlescreen to the game and loading into the main scene/exiting the game. Everything works as expected


## Legibility and Style
_Uses agreed coding standards/conventions? Readable, consistent and well-structured with useful comments?_  

 - Pretty much fine here. Some code thats commented out that we could remove but really isnt an issue as it related to debugging which could be helpful if we ever need it
 - A bit unfamiliar with the formatting of code in ExitGame() but I assume this is something you need for the UI_Toolkit. Again everything works so not an issue at all
```txt
	#if UNITY_EDITOR
            UnityEditor.EditorApplication.isPlaying = false;
        #else
            Application.Quit();
        #endif
```

_Any repetitive code that could be refactored? (DRY)_  

 - None


## Correctness of the Code
_Is the code reliable, giving same results every time it runs? Does it function correctly?_  

 - Everything seems to work great with some useful debug logs


## Implementation
_Any notable performance/speed issues? Compatibility and Responsiveness on other platforms ?_  

 - No issues


# Final Comments

 - All approved to merge

***

**Comment by Carlson-Lee** [comment]
Please ignore anything related with mini game scene. It's supposed to be a new branch work! Thank you.

**Comment by DevonHenderson** [comment]
> Please ignore anything related with mini game scene. It's supposed to be a new branch work! Thank you.

No worries, will get on to the review now and will get my branch up for review later tonight

**Review by DevonHenderson — CHANGES_REQUESTED** [review]
# Code Review

_See previous review above for additional comments if necessary_

## Functional Requirements
_Is the application fit for purpose? Does it meet the the user’s requirements and properly address the issue?_  

 - Almost, the addition of the new fonts/style and background music add a lot to the previous work on the titlescreen scene. The dialogue box and text displaying looks great and will add a lot of charm to the game. 

 - Suggestions for changes
    - I would suggest that we change the volume the sound starting off playing at.  The volume was extremely loud through my headphones when set to 1 in Unity. Setting it to 0.1 seemed to be a bit better. 
    - There is an issue when resizing the game window that causes the background music to warp and not play correctly. See video below _(make sure volume is on before playing)_ _(Fix listed below video in separate image)_

https://github.com/Carlson-Lee/Dev-Carl-GameJam/assets/90590089/07483d4f-11ab-41fe-baf5-79674554cf66

**Sound warping: This can be fixed by changing the 'Doppler Level' in the 3D sound settings from 1 to 0**

image

 -  Clicking quickly while the dialogue is filling in causes the next dialogue to type at the same time, causing a jumbled mess of letters. We have to assume some players will just want to spam click through the story/dialogue and need it to complete the last message, then the next, instead of them overlapping. See the picture below for an example of clicking while the first dialogue is being printed to the screen.

image

 -  Clicking after all dialogue has shown current breaks the game, showing 'Index is out of range'. Need to make it so that the dialogue box just gets hidden if all necessary dialogue has been displayed.

 -  The keyboard sounds for the dialogue filling in doesn't really match up with the speed of the text so comes across as a bit confusing. The game also doesn't resolve around a computer/technology so we might want to change it to a more simple sound. I found a video and there is a few sounds the I feel would be more appropriate to the games theme. The sound at [1m30s in the video](https://youtu.be/B3S9QCCMPRw?si=KgXoQO-6BVuBDuUx&t=90) is more simple and could work a bit easier for any length of dialogue. Open to in-person discussion on this however and happy to keep it as is for now

## Legibility and Style
_Uses agreed coding standards/conventions? Readable, consistent and well-structured with useful comments?_  

 - Everything looks pretty good here. Although I'm not familiar with UI Toolkit it is structured well and I can tell what is going on. Good comments throughout the other scripts and use of the debug menu where it could be useful

_Any repetitive code that could be refactored? (DRY)_  

 - N/A

## Correctness of the Code
_Is the code reliable, giving same results every time it runs? Does it function correctly?_  

 - The issue of being able to 'see' multiple dialogues at once would need to be fixed


## Implementation
_Any notable performance/speed issues? Compatibility and Responsiveness on other platforms ?_  

 - Everything seems to be okay. Just the issue with 3D sound settings->Doppler Level->1 causing the sound to play incorrectly. Could be an issue if the user is playing in a windowed mode and chooses to resize their screen.


# Final Comments

 - Just a couple things to fix before this can be merged.
    - Fix the doppler level on both the background music and dialogue sound (set to 0)
    - Make it so only 1 dialogue will play at a time. Could add the feature so clicking fills in that whole dialogue, then clicking again clears the last dialogue and starts the next
    - Clicking after all dialogue is shown current breaks the game and stops 'play' mode. Might need to add something so that if all the dialogue required has been shown, then clicking again just sets the dialogue box to inactive (dialogueBox.SetActive(false))


# Future Considerations for the project

 - A couple things we will need to focus on when finalising the game will be:
   - Change the name from the Brain game placeholder to something that fits the theme we're creating a bit closer
   - Rename the scene from 'UI_Toolkit' to something like 'Titlescreen' or 'Main Menu'
   - Look at incorporating a option to mute sounds, change volume etc to suit the users preference
   - Change the background from completely white to a bit more of a dull white to reduce eye strain on the titlescreen

***

**Comment by Carlson-Lee** [comment]
I have kept the typing sound effect for now, and I do agree it doesn't fit our theme, it is just a placeholder til we find something better. 
I will work on the mute feature in a new branch.

**Review by DevonHenderson — APPROVED** [review]
All the new changes look great!

The pull request fixes the following from the last review:
 - Menu scene renamed for clarity
 - Starting Volume and doppler issue
 - Can only show 1 dialogue at a time
 - Dialogue no longer stops game when reaching end
 - Titlescreen colour brightness reduced which is easier on the eyes

All approved to merge _(also will need to change the branch merging into from main -> staging)_

**Pull request merged**
